export const SITE = {
  name: 'SM Luxury Chauffer',
  legalName: 'SM Luxury Chauffer',
  url: 'https://smluxurychauffer.it',
  email: 'info@smluxurychauffer.it',
  phone: '+390209952588',
  phoneDisplay: '+39 02 099 52588',
  whatsapp: '390209952588',
  address: {
    street: 'Via Eugenio Chiesa 4',
    locality: 'Milano',
    postalCode: '20122',
    region: 'Lombardia',
    country: 'IT',
  },
  geo: {
    latitude: 45.4642,
    longitude: 9.19,
  },
  founded: '2014',
  rating: { value: '5.0', count: '120' },
} as const;

export const AREAS_SERVED = [
  'Milano',
  'Monza',
  'Brianza',
  'Monza e Brianza',
  'Como',
  'Lecco',
  'Bergamo',
  'Varese',
  'Lodi',
  'Pavia',
  'Lombardia',
  'Malpensa',
  'Linate',
  'Orio al Serio',
  'Lago di Como',
  'Sankt Moritz',
  'Lugano',
  'Verona',
  'Torino',
  'Bologna',
  'Roma',
] as const;
